title: Neongraal @ github
email: blog@scifi.geek.nz
github_username:  neongraal
description: My Github pages site
theme: minima
show_excerpts: true
page_excerpts: true
paginate: 5

defaults:
  - scope:
      path: ""
    values:
      author: "@NeonGraal"

years:
  - 2022

# Archives
collections:
  archives:
    output: true
    permalink: /archives/:path/

plugins:
  - jekyll-feed