title: Neongraal.github.io
email: blog@scifi.geek.nz
github_username:  neongraal
description: My Github pages site
theme: minima

defaults:
  - scope:
      path: ""
    values:
      author: "@NeonGraal"

years:
  - 2022

# Archives
collections:
  archives:
    output: true
    permalink: /archives/:path/

plugins:
  - jekyll-feed