title: Neongraal.github.io
description: My Github pages site
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

# Archives
collections:
  archives:
    output: true
    permalink: /archives/:path/

gems:
  - jekyll-mentions
